<?xml version="1.0"?>
<robot name="sangi" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
      iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
      izz="${m*r*r/2}"
    />
  </macro>

  <macro name="box_inertia" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
      iyy="${m*(x*x+z*z)/12}" iyz = "0"
      izz="${m*(x*x+z*z)/12}"
    />
  </macro>

  <macro name="sphere_inertia" params="m r">
    <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
      iyy="${2*m*r*r/5}" iyz = "0"
      izz="${2*m*r*r/5}"
    />
  </macro>
  <macro name="wheel" params="lr tY">
	  <link name="${lr}_wheel">
	    <collision>
	      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
	      <geometry>
		<cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
	      </geometry>
	    </collision>

	    <visual>
	      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
	      <geometry>
		<cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
	      </geometry>
	      <material name="black"/>
	    </visual>

	    <inertial>
	      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
	      <mass value="${wheelMass}"/>
	      <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
	    </inertial>
	  </link>

	  <gazebo reference="${lr}_wheel">
	    <mu1 value="100.0"/>
	    <mu2 value="100.0"/>
	    <kp  value="10000000.0" />
	    <kd  value="1.0" />
	    <fdir1 value="1 0 0"/>
	    <material>Gazebo/Black</material>
	  </gazebo>


	  <joint name="${lr}_wheel_hinge" type="continuous">
	    <parent link="chassis"/>
	    <child link="${lr}_wheel"/>
	  <origin xyz="${-wheelPos+chassisLength/2} ${tY*wheelWidth/2+tY*chassisWidth/2} ${wheelRadius}" rpy="0 0 0" />
	    <axis xyz="0 1 0" rpy="0 0 0" />
	    <limit effort="100" velocity="100"/>
	    <joint_properties damping="0.0" friction="0.0"/>
	  </joint>


	  <transmission name="${lr}_trans">
	    <type>transmission_interface/SimpleTransmission</type>
	    <joint name="${lr}_wheel_hinge">
	      <hardwareInterface>EffortJointInterface</hardwareInterface>
	    </joint>
	    <actuator name="${lr}Motor">
	      <hardwareInterface>EffortJointInterface</hardwareInterface> 
	      <mechanicalReduction>10</mechanicalReduction>
	    </actuator>
	  </transmission>
  </macro>
    <xacro:macro name="sonar_sensor" params="name parent ros_topic origin_new rpy update_rate min_range max_range field_of_view ray_count">
    <joint name="${name}_joint" type="fixed">
      <!--<xacro:insert_block name="origin" />!-->
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>

    <link name="${name}_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="${origin_new}" rpy="${rpy}" />
        <inertia ixx="0.000000017" ixy="0" ixz="0" iyy="0.000000017" iyz="0" izz="0.000000017" />
      </inertial>
      <visual>
        <origin xyz="${origin_new}" rpy="${rpy}" />
        <geometry>
          <!--<box size="0.01 0.01 0.01" /> -->
          <mesh filename="package://sangi_description/meshes/sonar/ping_sonar.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="${origin_new}" rpy="${rpy}" />
        <geometry>
          <box size="0.05 0.05 0.05" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="${name}_link">
      <sensor type="ray" name="${name}">
        <always_on>true</always_on>
        <update_rate>${update_rate}</update_rate>
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <ray>
          <scan>
            <horizontal>
              <samples>${ray_count}</samples>
              <resolution>1</resolution>
              <min_angle>-${field_of_view/2}</min_angle>
              <max_angle> ${field_of_view/2}</max_angle>
            </horizontal>
            <vertical>
              <samples>${ray_count}</samples>
              <resolution>1</resolution>
              <min_angle>-${field_of_view/2}</min_angle>
              <max_angle> ${field_of_view/2}</max_angle>
            </vertical>
          </scan>
          <range>
            <min>${min_range}</min>
            <max>${max_range}</max>
            <resolution>0.01</resolution>
          </range>
        </ray>

        <plugin name="gazebo_ros_${name}_controller" filename="libhector_gazebo_ros_sonar.so">
          <gaussianNoise>0.005</gaussianNoise>
          <topicName>${ros_topic}</topicName>
          <frameId>${name}_link</frameId>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>

</robot>
